### ISSUE TITLE
 Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by rmdes** [brandongallagher1999/CrypTorrents-React-FastAPI#81]
Hello, I've managed to run your code and have my two docker images running fine
but when I do a search in the frontend, I get CORS errors. 

Cross-Origin Request Blocked: The Same Origin Policy disallows
reading the remote resource at http://localhost:5000/api/torrents/get/MovieName

is there anything I can do to go around this problem?

Also perhaps integrating this : https://www.npmjs.com/package/cors-anywhere would help ?

**Comment by brandongallagher1999** [comment]
Hello Ricardo,

Is CORS-Anywhere a package more catered towards running servers?

Also, I'll investigate this bug today and will get back to you with a reply.

**Comment by brandongallagher1999** [comment]
I've identified some bugs, and am fixing them now. This is due to updates in the dependencies and not updating the code as a result. This is because I haven't touched this repo in many months at this point.

**Comment by brandongallagher1999** [comment]
@rmdes With the new commit, (pushed directly to master, I know bad practice but I'm tired this morning), all issues related to react deps upgrade and docker have been fixed.

It will now run via a "docker-compose up" command. The only problem is the data the used to be returned to the front end as a table no (about a year ago) no longer returns anything as ThePirateBay changed their data tables and url pathing.

Unfortunately, when ThePirateBay makes a change to their frontend in production, it affects my app as it scrapes the website.

I ran my tests and you should be all good to go in terms of actually running it and seeing what the app would look like without TPB data.

https://github.com/brandongallagher1999/CrypTorrents-React-FastAPI/commit/a9ac88868a13eb8e11bcf826903f0d0fec8626dd

**Comment by rmdes** [comment]
Hello Brandon, thanks a lot for taking the time to update the code, I removed previous build images, pruned everything and built & composed-up with the latest code. Sadly I'm still getting the same issue

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/api/torrents/?torrent=Dune. (Reason: CORS request did not succeed).

For testing purpose I connected to localhost:3000 using a tunneled ssh connection, when I do so, the CORS errors are gone but I can't get any results to display, probably something is wrong on my side but I'm getting out of ideas to have this running properly. 

My stack is Debian 10 / Docker version 20.10.9, build c2ea9bc
frontend can be accessed from here : http://vmsdt-mendes.becode.org:3000/

I was thinking that maybe I could solve this by associating a proper hostname to the app, so I created a .env file
and specified a HOST and PUBLIC_URL like specified here https://create-react-app.dev/docs/advanced-configuration/
but it does not change anything

So I started to dig more about the issue between fastAPI and Cors and it seems
this could be a solution : https://github.com/tiangolo/fastapi/issues/1663#issuecomment-738075572
but I'm not sure (and I don't know enough about coding) if this relate to your code. 

https://fastapi.tiangolo.com/tutorial/cors/

**Comment by brandongallagher1999** [comment]
That solution is already implemented into my code. As of why you're unable to request the backend via the front end is unknown to me. After cloning the repo, and running it with docker-compose, it seems to be working fine for me.

`python

origins = ["http://localhost:3000"]

# TODO: Change origin to real domain to reject Ajax requests from elsewhere
app.add_middleware(CORSMiddleware, allow_origins=origins, allow_methods=["*"], allow_headers=["*"])

`

**Comment by rmdes** [comment]
Sorry, I saw it was while exploring main.py from the backend folder after writing this comment ! my bad!

for the sake of testing I added my full hostname + port to the origin variable, built & run the containers
but I'm still stuck in the same situation (i'm running this on a Vsphere/Debian intranet)
I'm going to test this locally in my machine and if all run smooth this "issue" can be close :)

**Comment by rmdes** [comment]
For the sake of sharing information :  I tested the CORS issue with a SSH Dynamic Port Forwarding
so when, locally I visit localhost:3000 it forwards the target to my ssh tunnel. 

With this, when I request a search in the front end, I see the request hitting the backend server log 
│   INFO:     Started server process [1]                                                                           │
│   INFO:     Waiting for application startup.                                                                     │
│   INFO:     Application startup complete.                                                                        │
│   INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)                                        │
│   INFO:     172.19.0.1:41216 - "OPTIONS /api/torrents/?torrent=Dune HTTP/1.1" 200 OK                             │
│   INFO:     172.19.0.1:41216 - "GET /api/torrents/?torrent=Dune HTTP/1.1" 200 OK   

But, even though there is no more CORS issue using this approach, I don't get any results...

![image](https://user-images.githubusercontent.com/12155003/142437120-b2b5aead-22c6-4482-a3cd-9863f5819875.png)

**Comment by brandongallagher1999** [comment]
Try pulling the latest version. I noticed that the get request was from the
older version.

**Comment by brandongallagher1999** [comment]
As I said before in a previous comment, it won't return any results as ThePirateBay scraping library is broken since it wasn't updated to properly scrape their new front-end. 

> Unfortunately, when ThePirateBay makes a change to their frontend in production, it affects my app as it scrapes the website.

> I ran my tests and you should be all good to go in terms of actually running it and seeing what the app would look like 

> without TPB data.
